### ISSUE TITLE
Doesn't work over an app in full screen

### ISSUE THREAD

**Issue by djcastaldo** [maximbilan/Mac-OS-X-App-Menu-Bar-Popup#2]
I need my popover to display over a full screen safari or mail.  I was looking for a hint here, but this app fails at displaying when another app is in full screen.

**Comment by maximbilan** [comment]
Hi @djcastaldo,

Could please attach a video or a screenshot? I've just checked, it works over the safari or the mail client in full-screen mode. Thanks.

**Comment by djcastaldo** [comment]
https://citybase.synology.me/popoverError.mov

**Comment by maximbilan** [comment]
Thanks for reporting the bug.
I've fixed the bug. Please use the latest commit from the master branch.

**Comment by djcastaldo** [comment]
What did you change to get this to work?

**Comment by maximbilan** [comment]
@djcastaldo I've added
`<key>LSUIElement</key>
<true/>`
to Info.plist file.

**Comment by djcastaldo** [comment]
Is there a way to have this key, but still show a dock icon?

**Comment by maximbilan** [comment]
@djcastaldo I don't know.
